routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('posts', 'Admin\PostsController');

Route::group(['prefix' => 'gerant', 'namespace' => 'Admin', 'middleware' => ['auth', 'auth.gerant']], function() {
    Route::resource('films', 'FilmsController');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'auth.admin']], function(){

    Route::resource('categories', 'CategoriesController');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Models/Films.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Films extends Model
{
    //
    protected $guarded = ['id'];

    public function genre(){
        return $this->belongsTo('App\Models\Genre');
    }
}

app/Http/Controllers/Admin/FilmsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Films;
use App\Models\Genre;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FilmsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $title = "All films ";
        $films = Films::with('genre')->orderBy('id','DESC')->get();
        return view('films.index', compact('title','films'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $genres = Genre::orderBy('nom')->get();
        $title = 'New Film' ;
        return view('films.create', compact('title','genres'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // //persistance ds la bd
        Films::create($request->except(['_token']));
        return redirect()->route('films.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = "Edit film " ;
        $film= Films::find($id);
        if (!$film) return redirect()->route('films.index');
        $genres = Genre::orderBy('nom')->get();
        return view('films.edit', compact('title','genres','film'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $film= Films::find($id);
        if (!$film) return redirect()->route('films.index');
        $film->update($request->except(['_token', '_method'])) ;
        return redirect()->route('films.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if ($film = Films::find($id)){
            $film->delete() ;
        }
        return redirect()->route('films.index');
    }
}

app/Http/Controllers/Api/FilmsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Films;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FilmsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $films = Films::get() ;
        return response()->json($films);

//
//            ->where('date_sortie',)
//
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/films/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $title }}</div>
                    <div class="panel-body">
                        @if(count($errors) > 0)
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    <p>{{ $error }}</p>
                                @endforeach
                            </div>
                        @endif
                        <form action="{{ route('films.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="">Title</label>
                                <input type="text" name="nom" class="form-control" value="{{ old('nom') }}"
                                       placeholder="Film Title">
                            </div>

                            <div class="form-group">
                                <label for="">Auteur</label>
                                <input type="text" name="auteur" class="form-control" value="{{ old('auteur') }}"
                                       placeholder="auteur du Film ">
                            </div>

                            <div class="form-group">
                                <label for="">Date de sortie</label>
                                <input type="date" name="date_sortie" class="form-control" value="{{ old('date_sortie') }}">
                            </div>
                            <div class="form-group">
                                <label for="">Disponible</label>

                                <input type="number" name="disponible" class="form-control" value="{{ old('disponible') }}">
                            </div>

                            <div class="form-group">
                                <label for="">Genre</label>
                                <select name="genre_id" class="form-control">
                                    <option value="1">Select Gender</option>
                                    @foreach($genres as $g)
                                        <option value="{{ $g->id }}" {{ (old('genre_id') == $g->id) ? 'selected' : '' }}>{{ $g->nom }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <button class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/films/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: chebbi
 * Date: 21/11/2016
 * Time: 09:24
 */

resources/views/films/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $title }}</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <a href="{{ route('films.create') }}" class="btn btn-primary">New Film</a>
                        </div>
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Genre</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($films as $f)
                                <tr>
                                    <td>{{ $f->id }}</td>
                                    <td>{{ $f->title }}</td>
                                    <td>{{ $f->genre->name }}</td>
                                    <td>
                                        <a href="{{ route('films.edit', $p->id) }}"
                                           class="btn btn-default btn-xs">Edit</a>
                                        <form action="{{ route('films.destroy', $p->id) }}" class="form-delete"
                                              method="post">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button class="btn btn-xs btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@section('scripts')
    <script>
        $(function () {
            $('.form-delete').submit(function (e) {
                if (!confirm('Are you sure to delete this item?')) {
                    e.preventDefault();
                }
            });
        })
    </script>
@stop